# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
          cache: 'pip'

      - name: Install dependencies
        run: |
          PYTHONUNBUFFERED=1
          pip install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          pytest --disable-pytest-warnings --cov=src --cov-report xml -n auto

      - uses: codecov/codecov-action@v1
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/gcloud-shape-of-image' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Upload coverage data to coveralls.io
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/gcloud-shape-of-image' }}
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ github.token }}
